[tool.pytest.ini_options]
testpaths = "tests"
automark_dependency = true
addopts = "--order-dependencies -rA"

[tool.coverage.run]
branch = true
omit = [
    "*/__init__.py",
    "*/__version__.py",
]
include = ["scripts/*"]

[tool.pycln]
all = true

[tool.isort]
profile = "black"

[tool.black]
target-version = ['py38']
