#!/bin/bash

deactivate || true 2>/dev/null

# No need to set TS_REPO_ROOT here. Will be set to each subfolder in examples
# by tests!

# Generate temporary file which will configure SW
ts_sw_cfg.py -v ts_sw_setup.yml

# Source it and get rid of it
source ./source_me_to_get_all_set
rm source_me_to_get_all_set

# Append HW scripts
export PATH=$PATH:`pwd`/scripts

# Activate autocomplete for python scripts with PYTHON_ARGCOMPLETE_OK
temp_file=$(mktemp)
activate-global-python-argcomplete --dest=- > $temp_file
source $temp_file
rm $temp_file

# Add python environment
source $TS_PYTHON_ENV/bin/activate
